'use client';
import {useEffect,useRef,useState} from 'react';
import {Slider} from '@/components/ui/slider';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {solar,phase,dateLabel,season,stops} from '@/lib/solar';
import Scene3D from './Scene3D';
import DayNight from './DayNight';
import {Sun,Moon,RotateCcw,Play,Pause,HelpCircle,Globe,Clock} from 'lucide-react';

function SunView({altitude}:{altitude:number}){const a=Math.max(-15,altitude)*Math.PI/180;const x=Number((150-112*Math.cos(a)).toFixed(5)),y=Number((159-112*Math.sin(a)).toFixed(5));return <svg className="sun-view" viewBox="0 0 260 220" role="img" aria-label={`正午太陽高度角${altitude.toFixed(1)}度`}><defs><linearGradient id="sky" x2="0" y2="1"><stop stopColor={altitude>0?'#4e9bd8':'#101b38'}/><stop offset="1" stopColor={altitude>0?'#cce6ef':'#53607c'}/></linearGradient></defs><rect width="260" height="220" fill="url(#sky)"/>{altitude>0&&<><circle cx={x} cy={y} r="15" fill="#ffdb77"/><path d={`M${x},${y} L150,159`} stroke="#ffe3a0" strokeWidth="2"/><path d={`M${x+15},${y+4} L175,159`} stroke="#ffe3a066" strokeWidth="2"/></>}<rect y="159" width="260" height="61" fill="#425f34"/><ellipse cx="168" cy="159" rx={Math.min(75,14+50*(1-Math.max(0,altitude)/90))} ry="3" fill="#172b3566"/><circle cx="150" cy="109" r="9" fill="#f5a126"/><circle cx="145" cy="107" r="1.7" fill="#24374c"/><path d="M150 120 L150 139 M144 126 L140 140 M156 126 L160 140 M147 139 L147 157 M153 139 L153 157" stroke="#e58d18" strokeWidth="7" strokeLinecap="round"/>{altitude>0?<text x="174" y="144" fill="white" fontSize="14">{altitude.toFixed(1)}°</text>:<text x="20" y="40" fill="white" fontSize="15">太陽在地平線下</text>}</svg>}
const questions=[
 {q:'地球上的四季主要由甚麼造成？',a:['地球與太陽的距離改變','地軸傾斜，加上地球繞太陽公轉','太陽每年改變大小'],correct:1,why:'地軸傾斜約23.5°。地球公轉時，不同半球的日照角度和晝長會改變。'},
 {q:'6月21日前後，北半球和南半球的季節有甚麼關係？',a:['兩者都是夏季','北半球是冬季，南半球是夏季','北半球是夏季，南半球是冬季'],correct:2,why:'同一時間，南北半球朝向太陽的傾斜情況相反，所以季節相反。'},
 {q:'同一地點的正午太陽高度角越大，陽光通常怎樣？',a:['照射越集中，單位面積得到的能量越多','照射越分散','一定完全沒有影子'],correct:0,why:'高度角越大，同一束陽光照射的地面面積越小，單位面積得到的能量越多。'},
 {q:'春分、秋分前後，大部分地區的晝長和夜長怎樣？',a:['日間24小時','日夜大約各12小時','夜間比日間長一倍'],correct:1,why:'春分和秋分時太陽直射赤道，大部分地區的晝夜長度大致相同。'},
 {q:'地球公轉一周時，地軸的指向會怎樣？',a:['一直指向太陽','每個月反轉一次','大致保持相同方向'],correct:2,why:'地軸在一年中大致指向同一方向，不會一直轉向太陽。'}
];
function SeasonsPage({onHome}:{onHome:()=>void}){
 const [day,setDay]=useState(276),[lat,setLat]=useState(30),[hemi,setHemi]=useState('north'),[axis,setAxis]=useState(true),[inquiry,setInquiry]=useState(true),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState('1'),[light,setLight]=useState(false),[view,setView]=useState(0),[modal,setModal]=useState(''),[qi,setQi]=useState(0),[answer,setAnswer]=useState<number|null>(null),[score,setScore]=useState(0),[done,setDone]=useState(false);
 const s=solar(day,lat), south=hemi==='south';const latitude=`${Math.abs(lat).toFixed(1)}° ${lat<0?'S':lat>0?'N':''}`;const date=dateLabel(day);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setDay(d=>(d+Number(speed)*.35)%365),40);return()=>clearInterval(timer);},[playing,speed]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'configure_seasons',description:'設定四季模型的公轉日數（春分起算）和觀測緯度，回傳日照數據。',inputSchema:{type:'object',properties:{day:{type:'number',minimum:0,maximum:364},latitude:{type:'number',minimum:-90,maximum:90}},required:['day','latitude'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!Number.isFinite(input.day)||input.day<0||input.day>364||!Number.isFinite(input.latitude)||Math.abs(input.latitude)>90)throw new Error('日期或緯度超出範圍');setPlaying(false);setDay(input.day);setLat(input.latitude);setHemi(input.latitude<0?'south':'north');return solar(input.day,input.latitude);}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
 function hemisphere(h:string){setHemi(h);setLat(l=>h==='south'?-Math.abs(l):Math.abs(l));}
 function open(m:string){setPlaying(false);setModal(m);}
 function reset(){setDay(276);setLat(30);setHemi('north');setPlaying(false);setSpeed('1');setAxis(true);setView(v=>v+1);setInquiry(true);}
 function quiz(){setQi(0);setAnswer(null);setScore(0);setDone(false);open('quiz');}
 function next(){if(qi===4){setDone(true);return;}setQi(qi+1);setAnswer(null);}
 return <main className={`simulator ${light?'light-mode':''}`}>
 <div className="stars" aria-hidden="true"/>
 <header className="topbar"><div className="brand"><Sun size={29}/><div><h1>四季模擬器・教學版</h1><p>地球自轉與公轉，觀察正午日照</p></div></div><nav><button onClick={onHome}>返回主題</button><button onClick={()=>open('learn')}>學習任務</button><button className="icon-button" aria-label="重設模擬" onClick={reset}><RotateCcw size={19}/></button><button className="icon-button" aria-label="切換深色或淺色模式" onClick={()=>setLight(!light)}>{light?<Sun size={19}/>:<Moon size={19}/>}</button></nav></header>
 <section className="space"><Scene3D day={day} axis={axis} lat={lat} light={light} resetToken={view} south={south}/></section>
 <aside className="panel data-panel" aria-label="日期與季節資訊"><h2>{date}</h2><p className="season-tag">● {south?'南':'北'}半球：{inquiry?'先用證據判斷':season(day,south)}</p><RadioGroup value={hemi} onValueChange={hemisphere} className="pill-group" aria-label="比較半球">{[['north','北半球視角'],['south','南半球視角']].map(([v,t])=><label key={v} className={hemi===v?'selected':''}><RadioGroupItem value={v} aria-label={t}/>{t}</label>)}</RadioGroup><div className="stats"><div><span>地軸傾角</span><strong>23.5°</strong></div><div><span>觀測者緯度</span><strong>{latitude}</strong></div><div><span>太陽高度角</span><strong data-testid="altitude">{s.altitude.toFixed(1)}°</strong></div><div><span>晝長 / 夜長</span><strong data-testid="daylight">{s.daylight.toFixed(1)}h /<br/>{s.night.toFixed(1)}h</strong></div></div>{s.daylight===24||s.daylight===0?<p className="polar-note">{s.daylight===24?'極晝：太陽整天不落下':'極夜：太陽整天不升起'}</p>:null}</aside>
 <aside className="panel observer-panel" aria-label="觀測者視角"><h3><Sun size={16}/> 觀測者視角：陽光照射</h3><SunView altitude={s.altitude}/><div className="intensity"><strong>{Math.round(s.intensity)}%</strong><span>正午相對日照強度</span></div><div className="meter"><div style={{width:`${s.intensity}%`}}/></div><dl><div><dt>太陽入射角</dt><dd>{s.altitude<0?'—':`${s.incidence.toFixed(1)}°`}</dd></div><div><dt>照射方式</dt><dd className="badge">{s.altitude<=0?'無日照':s.altitude>89.5?'直射':'斜射'}</dd></div><div><dt>觀測者位置</dt><dd>固定正午</dd></div></dl><p className="small-note">入射角由地面法線量度；強度以垂直照射為100%。</p></aside>
 <section className="panel controls" aria-label="模擬控制"><label className="check-label"><Checkbox checked={inquiry} onCheckedChange={v=>setInquiry(v===true)} aria-label="探究模式"/> 探究模式：隱藏目前季節提示</label><p className="date-hemi">日期季節：{south?'南':'北'}半球</p><div className="dates">{['3月20日','6月21日','9月22日','12月21日'].map((t,i)=><button key={t} aria-pressed={Math.abs(day-stops[i])<1} onClick={()=>{setPlaying(false);setDay(stops[i]);}}>{t}{`（${['春','夏','秋','冬'][(i+(south?2:0))%4]}）`}</button>)}</div><div className="slider-title"><label id="time-label"><Clock size={15}/> 時間（一年公轉進度）</label><span>{date}</span></div><Slider aria-labelledby="time-label" value={[day]} min={0} max={364} step={1} onValueChange={v=>{setPlaying(false);setDay(v[0]);}}/><div className="bottom-controls"><div className="latitude-control"><div className="slider-title"><label id="lat-label"><Globe size={15}/> 觀測者緯度</label><span>{latitude}</span></div><Slider aria-labelledby="lat-label" value={[lat]} min={-90} max={90} step={.5} onValueChange={v=>{setLat(v[0]);if(v[0]!==0)setHemi(v[0]<0?'south':'north');}}/></div><button className="play-button" aria-label={playing?'暫停公轉':'播放公轉'} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={19}/>:<Play size={19} fill="currentColor"/>}</button><RadioGroup value={speed} onValueChange={setSpeed} className="pill-group speed-group" aria-label="播放速度">{['0.5','1','3'].map(v=><label key={v} className={speed===v?'selected':''}><RadioGroupItem value={v} aria-label={`${v}倍速度`}/>{v}×</label>)}</RadioGroup><label className="axis-label">顯示地軸 <Switch checked={axis} onCheckedChange={setAxis} aria-label="顯示地軸"/></label></div></section>
 <footer><button onClick={()=>open('about')}>▸ 模型說明</button><button className="quiz-button" onClick={quiz}><HelpCircle size={19}/> 小測驗 <span>5</span></button></footer>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v)setModal('');}}><DialogContent className="teaching-dialog"><DialogTitle>{modal==='learn'?'學習任務':modal==='about'?'模型說明':'四季小測驗'}</DialogTitle><DialogDescription>{modal==='learn'?'先預測，再操作模型，最後用數據解釋。':modal==='about'?'了解模型如何表示真實世界。':'運用剛才觀察到的證據作答。'}</DialogDescription>
 {modal==='about'&&<div className="prose"><p>地軸與公轉軌道面的垂直方向夾角約為23.5°，公轉時大致保持相同指向。</p><p>本模型放大了太陽和地球，距離、大小及公轉速度不按真實比例；軌道簡化為圓形，節氣日期採用教學用近似值。</p><p>地球表面會自轉；橙色小人是「正午定位標記」，會沿所選緯度調整經度，保持面向太陽，並非固定在同一地面的居民。極夜時，即使在正午，太陽仍在地平線下。自轉與公轉播放速度經過調整，方便觀察。右方視窗固定在觀測者的正午。太陽高度角由地平線量起；入射角則由垂直地面的方向量起。兩者在太陽位於地平線上時相加為90°。</p><p>晝夜長度不計大氣折射、地形及太陽視直徑；日照強度只反映照射角度，並非天氣預報或實際氣溫。</p><p>北極和南極在春分、秋分當天，太陽接近地平線；模型以12小時作過渡近似。</p></div>}
 {modal==='learn'&&<div className="tasks">{[{title:'比較同一地點的夏天與冬天',text:'設定北緯30°，比較6月21日和12月21日。哪天的正午太陽較高？哪天日間較長？',d:93,l:30},{title:'南北半球的季節一樣嗎？',text:'保持6月21日，切換南北半球視角。比較兩地的太陽高度角和晝長。',d:93,l:-30},{title:'極地會整天看見太陽嗎？',text:'把觀測者移到北緯75°，比較6月和12月，尋找極晝和極夜。',d:93,l:75}].map((task,i)=><article key={task.title}><span>任務 {i+1}</span><h3>{task.title}</h3><p>{task.text}</p><button onClick={()=>{setDay(task.d);setLat(task.l);setHemi(task.l<0?'south':'north');setModal('');}}>開始這個任務</button></article>)}</div>}
 {modal==='quiz'&&(done?<div className="quiz-result"><Sun size={45}/><h3>完成了！</h3><p>答對 <strong>{score} / 5</strong> 題</p><p>再試着改變緯度，看看你的推論是否適用。</p><button onClick={quiz}>再試一次</button></div>:<div className="quiz-body"><p className="question-count">問題 {qi+1} / 5</p><h3>{questions[qi].q}</h3><div className="answers">{questions[qi].a.map((a,i)=><button key={a} disabled={answer!==null} className={answer===null?'':i===questions[qi].correct?'correct':i===answer?'incorrect':''} onClick={()=>{setAnswer(i);if(i===questions[qi].correct)setScore(score+1);}}>{String.fromCharCode(65+i)}. {a}</button>)}</div>{answer!==null&&<p className="feedback" role="status"><strong>{answer===questions[qi].correct?'答對了！':'再想一想。'}</strong>{questions[qi].why}</p>}<div className="quiz-actions"><button onClick={next}>跳過</button><button disabled={answer===null} onClick={next}>{qi===4?'查看結果':'下一題'}</button></div></div>)}
 </DialogContent></Dialog>
 </main>
}

export default function Home(){
 const [topic,setTopic]=useState('');
 useEffect(()=>{const read=()=>setTopic(['day-night','seasons'].includes(location.hash.slice(1))?location.hash.slice(1):'');read();window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read);},[]);
 function choose(value:string){window.location.hash=value;setTopic(value);window.scrollTo(0,0);}
 if(topic==='seasons')return <SeasonsPage onHome={()=>choose('')}/>;
 if(topic==='day-night')return <DayNight onHome={()=>choose('')}/>;
 return <main className="simulator topic-home"><div className="stars" aria-hidden="true"/><header className="topbar"><div className="brand"><Globe size={29}/><div><h1>地球觀察站</h1><p>日與夜・四季</p></div></div></header><section className="topic-picker"><p className="topic-eyebrow">選擇今天的探索主題</p><h2>你想觀察哪一種變化？</h2><div className="topic-cards"><button className="topic-card daily-card" onClick={()=>choose('day-night')}><span className="topic-icons"><Sun size={42}/><Moon size={36}/></span><span className="topic-name">日與夜</span><span className="topic-description">轉動地球，觀察同一地點的白天與黑夜。</span><span className="topic-meta">地球自轉・約 24 小時</span><span className="topic-enter">開始探索日與夜</span></button><button className="topic-card seasonal-card" onClick={()=>choose('seasons')}><span className="topic-icons"><Globe size={46}/><Sun size={32}/></span><span className="topic-name">四季</span><span className="topic-description">比較四季，觀察陽光照射與晝夜長短。</span><span className="topic-meta">地球公轉・約一年</span><span className="topic-enter">開始探索四季</span></button></div></section></main>;
}
