'use client';
import {useEffect,useRef,useState} from 'react';
// Three.js is bundled locally; no runtime CDN is used.
// @ts-ignore
import * as THREE from 'three';
// @ts-ignore
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {phase} from '@/lib/solar';
import {SoftwareRenderer} from './SoftwareRenderer';
import {Plus,Minus,Focus,RotateCcw,Pause,Play,Move} from 'lucide-react';

type Props={day:number;axis:boolean;lat:number;light:boolean;resetToken:number};
export default function Scene3D(props:Props){
 const mount=useRef<HTMLDivElement>(null),label=useRef<HTMLDivElement>(null),current=useRef(props),actions=useRef<any>(null),spin=useRef(true);current.current=props;
 const [spinning,setSpinning]=useState(true),[mode,setMode]=useState('overview'),[failed,setFailed]=useState(false),[moving,setMoving]=useState(false);const panMode=useRef(false);
 useEffect(()=>{
 const host=mount.current!;let renderer:any;
 try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});}catch{renderer=new SoftwareRenderer();}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.setAttribute('aria-label','立體太陽與地球模型：拖曳旋轉，滾輪或雙指縮放，方向鍵平移');renderer.domElement.setAttribute('tabindex','0');host.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(43,1,.05,180);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.1;controls.minDistance=2.6;controls.maxDistance=65;controls.enablePan=true;controls.screenSpacePanning=true;controls.rotateSpeed=.65;controls.zoomSpeed=.9;controls.keyPanSpeed=25;controls.listenToKeyEvents(renderer.domElement);
 const Y=new THREE.Vector3(0,1,0),north=new THREE.Vector3(-Math.sin(23.5*Math.PI/180),Math.cos(23.5*Math.PI/180),0),earthPos=new THREE.Vector3(),previousEarth=new THREE.Vector3();
 const tilt=new THREE.Quaternion().setFromUnitVectors(Y,north);let focus=false,first=true,lastTime=0,rotation=0,raf=0,disposed=false;
 const globeGroup=new THREE.Group();scene.add(globeGroup);const tilted=new THREE.Group();tilted.quaternion.copy(tilt);globeGroup.add(tilted);const surface=new THREE.Group();tilted.add(surface);
 // Geographic context: deliberately simplified continental outlines.
 const textureCanvas=document.createElement('canvas');textureCanvas.width=1024;textureCanvas.height=512;const tc=textureCanvas.getContext('2d')!;tc.fillStyle='#147bad';tc.fillRect(0,0,1024,512);
 const land=(points:number[][],color='#65ad65')=>{tc.fillStyle=color;tc.beginPath();points.forEach(([lon,lat],i)=>{const x=(lon+180)/360*1024,y=(90-lat)/180*512;i?tc.lineTo(x,y):tc.moveTo(x,y);});tc.closePath();tc.fill();tc.strokeStyle='#98c78c';tc.lineWidth=1;tc.stroke();};
 land([[-168,67],[-145,71],[-129,60],[-110,72],[-84,72],[-61,52],[-75,45],[-83,25],[-100,15],[-117,30],[-126,49],[-155,57]]);land([[-82,12],[-65,10],[-47,-2],[-35,-9],[-48,-30],[-70,-55],[-76,-26],[-81,-5]]);land([[-52,60],[-24,69],[-20,81],[-45,84],[-66,74]],'#cfe8d5');land([[-10,36],[-17,16],[-10,5],[9,1],[16,-17],[30,-35],[40,-14],[49,12],[34,30],[10,37]]);land([[-10,36],[-10,58],[5,71],[23,69],[40,57],[67,73],[114,73],[160,62],[179,51],[141,43],[131,31],[120,19],[106,5],[99,22],[79,7],[68,25],[48,29],[36,42],[23,37],[10,44]]);land([[112,-12],[132,-10],[153,-26],[146,-39],[129,-33],[114,-24]]);land([[47,-13],[50,-16],[47,-25],[44,-22]]);land([[130,32],[141,45],[145,44],[138,34]],'#83be75');land([[-180,-76],[-130,-71],[-80,-77],[-65,-64],[-50,-77],[0,-71],[60,-69],[110,-74],[180,-76],[180,-90],[-180,-90]],'#e0f2ed');
 tc.strokeStyle='#b4e9fa44';tc.lineWidth=1;for(let lon=-180;lon<=180;lon+=30){const x=(lon+180)/360*1024;tc.beginPath();tc.moveTo(x,0);tc.lineTo(x,512);tc.stroke();}for(let lat=-60;lat<=60;lat+=30){const y=(90-lat)/180*512;tc.beginPath();tc.moveTo(0,y);tc.lineTo(1024,y);tc.stroke();}
 const tex=new THREE.CanvasTexture(textureCanvas);tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
 const earth=new THREE.Mesh(new THREE.SphereGeometry(1,64,40),new THREE.MeshPhongMaterial({map:tex,shininess:12,specular:0x18333e}));surface.add(earth);
 const sun=new THREE.Mesh(new THREE.SphereGeometry(1.5,48,32),new THREE.MeshBasicMaterial({color:0xffdf89}));scene.add(sun);
 const glowCanvas=document.createElement('canvas');glowCanvas.width=128;glowCanvas.height=128;const gc=glowCanvas.getContext('2d')!;const gr=gc.createRadialGradient(64,64,20,64,64,64);gr.addColorStop(0,'rgba(255,216,128,.30)');gr.addColorStop(.5,'rgba(255,216,128,.10)');gr.addColorStop(1,'rgba(255,216,128,0)');gc.fillStyle=gr;gc.fillRect(0,0,128,128);const glowTex=new THREE.CanvasTexture(glowCanvas);const glow=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTex,transparent:true,depthWrite:false}));glow.scale.set(7,7,1);scene.add(glow);
 scene.add(new THREE.AmbientLight(0xffffff,.18));const sunlight=new THREE.DirectionalLight(0xffffff,2.6);sunlight.position.set(0,0,0);sunlight.target=globeGroup;scene.add(sunlight);
 const line=(points:any[],color:number,opacity=1)=>new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color,transparent:opacity<1,opacity}));
 const orbit=line(Array.from({length:181},(_,i)=>new THREE.Vector3(8*Math.cos(i/180*Math.PI*2),0,8*Math.sin(i/180*Math.PI*2))),0x557496,.7);scene.add(orbit);
 const axisLine=line([new THREE.Vector3(0,-1.55,0),new THREE.Vector3(0,1.55,0)],0xdbeafe);tilted.add(axisLine);
 const equator=line(Array.from({length:129},(_,i)=>new THREE.Vector3(1.012*Math.cos(i/128*Math.PI*2),0,1.012*Math.sin(i/128*Math.PI*2))),0xffd86f);tilted.add(equator);
 const latitudeLine=line(Array.from({length:129},()=>new THREE.Vector3()),0x43e5dd,.75);tilted.add(latitudeLine);
 function textSprite(text:string,color:string){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=80;const c=canvas.getContext('2d')!;c.fillStyle=color;c.beginPath();c.roundRect(0,5,256,70,30);c.fill();c.font='bold 40px sans-serif';c.textAlign='center';c.fillStyle='white';c.fillText(text,128,55);const map=new THREE.CanvasTexture(canvas);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map,depthTest:false,transparent:true}));sprite.scale.set(.72,.225,1);sprite.renderOrder=10;return sprite;}
 const northLabel=textSprite('北極','#a63c46'),southLabel=textSprite('南極','#a63c46');northLabel.position.set(0,1.78,0);southLabel.position.set(0,-1.78,0);tilted.add(northLabel,southLabel);
 const marker=new THREE.Group();globeGroup.add(marker);const personMat=new THREE.MeshBasicMaterial({color:0xff9d21}),whiteMat=new THREE.MeshBasicMaterial({color:0xfff8df}),darkMat=new THREE.MeshBasicMaterial({color:0x152c44});
 const part=(geo:any,mat:any,x:number,y:number,z:number)=>{const mesh=new THREE.Mesh(geo,mat);mesh.position.set(x,y,z);marker.add(mesh);return mesh;};
 part(new THREE.SphereGeometry(.105,18,12),personMat,0,.55,0);part(new THREE.CylinderGeometry(.09,.065,.23,14),personMat,0,.32,0);for(const x of [-.047,.047])part(new THREE.CylinderGeometry(.025,.025,.20,10),whiteMat,x,.13,0);for(const x of [-.12,.12]){const arm=part(new THREE.CylinderGeometry(.024,.024,.19,10),personMat,x,.31,.025);arm.rotation.z=x<0?-.35:.35;}for(const x of [-.035,.035])part(new THREE.SphereGeometry(.015,8,6),darkMat,x,.575,.092);part(new THREE.ConeGeometry(.035,.07,10),whiteMat,0,.54,.125).rotation.x=Math.PI/2;
 const baseRing=new THREE.Mesh(new THREE.TorusGeometry(.18,.025,8,36),new THREE.MeshBasicMaterial({color:0x36fff0}));baseRing.rotation.x=Math.PI/2;baseRing.position.y=.01;marker.add(baseRing);
 const sunArrow=new THREE.ArrowHelper(new THREE.Vector3(1,0,0),new THREE.Vector3(),.95,0xffe497,.2,.09);globeGroup.add(sunArrow);
 const guide=line([new THREE.Vector3(),new THREE.Vector3()],0xffdc82,.35);scene.add(guide);
 function overview(){focus=false;setMode('overview');controls.target.set(0,0,0);camera.position.set(0,11.5,26);controls.update();}
 function closeup(){focus=true;setMode('earth');const S=earthPos.clone().normalize().negate();const tangent=new THREE.Vector3().crossVectors(north,S).normalize();const dir=S.clone().multiplyScalar(3.5).add(tangent.multiplyScalar(5.1)).add(north.clone().multiplyScalar(2.2));controls.target.copy(earthPos);camera.position.copy(earthPos).add(dir);controls.update();}
 actions.current={zoom:(factor:number)=>{camera.position.sub(controls.target).multiplyScalar(factor).clampLength(controls.minDistance,controls.maxDistance).add(controls.target);controls.update();},overview,closeup,pan:(on:boolean)=>{panMode.current=on;controls.mouseButtons.LEFT=on?THREE.MOUSE.PAN:THREE.MOUSE.ROTATE;controls.touches.ONE=on?THREE.TOUCH.PAN:THREE.TOUCH.ROTATE;}};overview();
 const resize=()=>{const w=host.clientWidth,h=host.clientHeight;if(w<1||h<1)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(host);resize();
 const worldMarker=new THREE.Vector3(),S=new THREE.Vector3(),eqSun=new THREE.Vector3(),radial=new THREE.Vector3(),facing=new THREE.Vector3(),right=new THREE.Vector3(),basis=new THREE.Matrix4(),proj=new THREE.Vector3();let previousLat=NaN;
 function frame(now:number){if(disposed)return;const dt=Math.min((now-lastTime)/1000||0,.15);lastTime=now;const p=current.current,a=phase(p.day)-Math.PI/2;earthPos.set(8*Math.cos(a),0,8*Math.sin(a));if(focus&&!first){const delta=earthPos.clone().sub(previousEarth);camera.position.add(delta);controls.target.add(delta);}previousEarth.copy(earthPos);first=false;globeGroup.position.copy(earthPos);S.copy(earthPos).normalize().negate();if(spin.current)rotation+=dt*.32;surface.rotation.y=rotation;axisLine.visible=p.axis;northLabel.visible=p.axis;southLabel.visible=p.axis;
 const phi=p.lat*Math.PI/180;eqSun.copy(S).addScaledVector(north,-S.dot(north)).normalize();radial.copy(north).multiplyScalar(Math.sin(phi)).addScaledVector(eqSun,Math.cos(phi)).normalize();marker.position.copy(radial).multiplyScalar(1.03);
 facing.copy(S).addScaledVector(radial,-S.dot(radial));if(facing.lengthSq()<1e-8)facing.copy(north).addScaledVector(radial,-north.dot(radial));facing.normalize();right.crossVectors(radial,facing).normalize();basis.makeBasis(right,radial,facing);marker.quaternion.setFromRotationMatrix(basis);
 sunArrow.position.copy(marker.position).addScaledVector(radial,.64);sunArrow.setDirection(S);worldMarker.copy(marker.position).add(earthPos);const positions=guide.geometry.attributes.position;positions.setXYZ(0,worldMarker.x,worldMarker.y,worldMarker.z);positions.setXYZ(1,0,0,0);positions.needsUpdate=true;
 if(previousLat!==p.lat){const points=latitudeLine.geometry.attributes.position;for(let i=0;i<129;i++){const t=i/128*Math.PI*2;points.setXYZ(i,1.016*Math.cos(phi)*Math.cos(t),1.016*Math.sin(phi),1.016*Math.cos(phi)*Math.sin(t));}points.needsUpdate=true;previousLat=p.lat;}
 controls.update();renderer.render(scene,camera);
 const labelWorld=worldMarker.clone().addScaledVector(radial,.95);proj.copy(labelWorld).project(camera);const w=host.clientWidth,h=host.clientHeight,x=(proj.x*.5+.5)*w,y=(-proj.y*.5+.5)*h;const visible=proj.z<1&&x>0&&x<w&&y>0&&y<h;if(label.current){label.current.style.display=visible?'block':'none';label.current.style.left=`${Math.max(74,Math.min(w-74,x))}px`;label.current.style.top=`${Math.max(75,Math.min(h-45,y))}px`;const behind=radial.dot(camera.position.clone().sub(earthPos).normalize())<-.04;label.current.dataset.behind=String(behind);const state=label.current.querySelector('small');if(state)state.textContent=behind?'位於地球背面 · 拖曳查看':'正午定位 · 面向太陽';}
 // Expose compact rendered state for accessibility and deterministic geometry checks.
 renderer.domElement.dataset.renderer=renderer instanceof SoftwareRenderer?'canvas3d':'webgl';renderer.domElement.dataset.spin=rotation.toFixed(4);renderer.domElement.dataset.camera=camera.position.toArray().map((v:number)=>v.toFixed(3)).join(',');renderer.domElement.dataset.observer=radial.toArray().map((v:number)=>v.toFixed(6)).join(',');renderer.domElement.dataset.sun=S.toArray().map((v:number)=>v.toFixed(6)).join(',');renderer.domElement.dataset.day=p.day.toFixed(2);renderer.domElement.dataset.mode=focus?'earth':'overview';
 raf=requestAnimationFrame(frame);}
 raf=requestAnimationFrame(frame);
 return()=>{disposed=true;cancelAnimationFrame(raf);ro.disconnect();controls.dispose();scene.traverse((o:any)=>{o.geometry?.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach((m:any)=>{if(m){m.map?.dispose();m.dispose();}});});renderer.dispose();renderer.domElement.remove();actions.current=null;};
 },[]);
 useEffect(()=>{actions.current?.overview();},[props.resetToken]);
 return <div className="scene3d-shell"><div ref={mount} className="scene3d-mount"/><div className="camera-toolbar" aria-label="立體模型視角控制"><button aria-label="放大模型" onClick={()=>actions.current?.zoom(.8)}><Plus size={18}/></button><button aria-label="縮小模型" onClick={()=>actions.current?.zoom(1.25)}><Minus size={18}/></button><button aria-pressed={mode==='earth'} onClick={()=>actions.current?.closeup()}><Focus size={17}/>聚焦地球</button><button onClick={()=>actions.current?.overview()} aria-label="重設全景視角"><RotateCcw size={17}/><span>全景</span></button><button aria-label="拖曳平移模式" aria-pressed={moving} onClick={()=>{setMoving(!moving);actions.current?.pan(!moving);}}><Move size={17}/></button></div><div ref={label} className="observer-marker-label"><strong>● 觀測者</strong><small>正午定位 · 面向太陽</small></div><div className="scene-help"><span>拖曳旋轉 · 滾輪／雙指縮放 · 右鍵拖曳平移</span><button aria-label={spinning?'暫停地球自轉':'恢復地球自轉'} onClick={()=>{spin.current=!spinning;setSpinning(!spinning);}}>{spinning?<Pause size={13}/>:<Play size={13}/>} 自轉{spinning?'中':'已暫停'}</button></div>{failed&&<div className="scene-error">此瀏覽器未能啟動立體模型。請使用支援 WebGL 的瀏覽器，或開啟硬體加速後重新整理。</div>}</div>;
}
