// Canvas renderer for browsers with WebGL disabled. Uses the same 3D scene,
// camera and OrbitControls as the accelerated renderer.
// @ts-ignore
import * as THREE from 'three';
export class SoftwareRenderer{
 domElement=document.createElement('canvas');capabilities={getMaxAnisotropy:()=>1};outputColorSpace:any;private ctx=this.domElement.getContext('2d')!;private ratio=1;private w=1;private h=1;private textureCache=new WeakMap<object,{data:Uint8ClampedArray,w:number,h:number}>();
 setPixelRatio(n:number){this.ratio=Math.min(n,1.5);}setClearColor(){}setSize(w:number,h:number){this.w=w;this.h=h;this.domElement.width=Math.round(w*this.ratio);this.domElement.height=Math.round(h*this.ratio);this.domElement.style.width=w+'px';this.domElement.style.height=h+'px';}dispose(){}
 render(scene:any,camera:any){scene.updateMatrixWorld();camera.updateMatrixWorld();const ctx=this.ctx,w=this.w,h=this.h;ctx.setTransform(this.ratio,0,0,this.ratio,0,0);ctx.clearRect(0,0,w,h);const vp=new THREE.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse);const draws:{z:number,paint:()=>void}[]=[];const project=(v:any)=>{const p=v.clone().applyMatrix4(vp);return {x:(p.x*.5+.5)*w,y:(-.5*p.y+.5)*h,z:p.z};};
 const litDir=new THREE.Vector3(1,0,0);scene.traverseVisible((o:any)=>{if(o.isDirectionalLight){const pos=new THREE.Vector3().setFromMatrixPosition(o.matrixWorld),target=new THREE.Vector3().setFromMatrixPosition(o.target.matrixWorld);litDir.copy(pos).sub(target).normalize();}});
 scene.traverseVisible((o:any)=>{const mat=o.material;if(!mat||mat.visible===false)return;
 if(o.isSprite){const center=new THREE.Vector3().setFromMatrixPosition(o.matrixWorld),p=project(center);if(p.z>1||p.z< -1)return;const scale=new THREE.Vector3();o.getWorldScale(scale);const distance=center.distanceTo(camera.position);const units=h/(2*Math.tan(camera.fov*Math.PI/360)*distance),sw=scale.x*units,sh=scale.y*units;draws.push({z:mat.depthTest===false?-10:p.z,paint:()=>{ctx.globalAlpha=mat.opacity??1;if(mat.map?.image)ctx.drawImage(mat.map.image,p.x-sw/2,p.y-sh/2,sw,sh);ctx.globalAlpha=1;}});return;}
 const geo=o.geometry;if(!geo?.attributes.position)return;const positions=geo.attributes.position,uvs=geo.attributes.uv,normals=geo.attributes.normal;const normalMatrix=new THREE.Matrix3().getNormalMatrix(o.matrixWorld);const projected:any[]=[],worlds:any[]=[];for(let i=0;i<positions.count;i++){const v=new THREE.Vector3().fromBufferAttribute(positions,i).applyMatrix4(o.matrixWorld);worlds.push(v);projected.push(project(v));}
 const color=mat.color??new THREE.Color('white');const rgb=(c:any,intensity=1)=>`rgb(${Math.round(Math.min(1,c.r*intensity)*255)},${Math.round(Math.min(1,c.g*intensity)*255)},${Math.round(Math.min(1,c.b*intensity)*255)})`;
 if(o.isLine||o.isLineSegments){const step=o.isLineSegments?2:1;for(let i=0;i<positions.count-1;i+=step){const a=projected[i],b=projected[i+1];if(a.z>1||b.z>1||a.z< -1||b.z< -1)continue;draws.push({z:(a.z+b.z)/2-.00001,paint:()=>{ctx.globalAlpha=mat.opacity??1;ctx.strokeStyle=rgb(color);ctx.lineWidth=1.3;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.globalAlpha=1;}});}return;}
 if(!o.isMesh)return;let texture:any;if(mat.map?.image){texture=this.textureCache.get(mat.map);if(!texture){const im=mat.map.image,c=document.createElement('canvas');c.width=im.width;c.height=im.height;const cc=c.getContext('2d')!;cc.drawImage(im,0,0);texture={data:cc.getImageData(0,0,c.width,c.height).data,w:c.width,h:c.height};this.textureCache.set(mat.map,texture);}}
 const idx=geo.index;const count=idx?idx.count:positions.count;for(let t=0;t<count;t+=3){const ai=idx?idx.getX(t):t,bi=idx?idx.getX(t+1):t+1,ci=idx?idx.getX(t+2):t+2;const a=projected[ai],b=projected[bi],c=projected[ci];if(a.z>1||b.z>1||c.z>1||a.z< -1||b.z< -1||c.z< -1)continue;const winding=(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);if(winding>=0&&mat.side!==THREE.DoubleSide)continue;if(Math.max(a.x,b.x,c.x)<0||Math.min(a.x,b.x,c.x)>w||Math.max(a.y,b.y,c.y)<0||Math.min(a.y,b.y,c.y)>h)continue;
 let intensity=1;if(!mat.isMeshBasicMaterial){const n=normals?new THREE.Vector3().fromBufferAttribute(normals,ai).add(new THREE.Vector3().fromBufferAttribute(normals,bi)).add(new THREE.Vector3().fromBufferAttribute(normals,ci)).applyNormalMatrix(normalMatrix):new THREE.Vector3().crossVectors(worlds[bi].clone().sub(worlds[ai]),worlds[ci].clone().sub(worlds[ai])).normalize();intensity=.12+.88*Math.max(0,n.dot(litDir));}
 let fill=rgb(color,intensity);if(texture&&uvs){const u=(uvs.getX(ai)+uvs.getX(bi)+uvs.getX(ci))/3,v=(uvs.getY(ai)+uvs.getY(bi)+uvs.getY(ci))/3;const x=Math.min(texture.w-1,Math.max(0,Math.floor(u*texture.w))),y=Math.min(texture.h-1,Math.max(0,Math.floor((1-v)*texture.h)));const ix=(y*texture.w+x)*4;fill=`rgb(${Math.round(texture.data[ix]*intensity)},${Math.round(texture.data[ix+1]*intensity)},${Math.round(texture.data[ix+2]*intensity)})`;}
 draws.push({z:(a.z+b.z+c.z)/3,paint:()=>{ctx.globalAlpha=mat.opacity??1;ctx.fillStyle=fill;ctx.strokeStyle=fill;ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(c.x,c.y);ctx.closePath();ctx.fill();ctx.stroke();ctx.globalAlpha=1;}});
 }
 });draws.sort((a,b)=>b.z-a.z);for(const d of draws)d.paint();
 }
}
